from enum import Enum
from typing import List, Optional, Any, Dict, Union
from datetime import datetime
from pydantic import BaseModel, Field, field_validator


class QueryIntent(str, Enum):
    """High-level analytical intention extracted by the LLM."""
    METRIC_AGGREGATION = "METRIC_AGGREGATION"        # e.g., "What is the average resolution time?"
    GROUPED_BREAKDOWN = "GROUPED_BREAKDOWN"          # e.g., "Show ticket count by category and priority"
    AGENT_PERFORMANCE = "AGENT_PERFORMANCE"          # e.g., "Who is the top performing agent?"
    TREND_ANALYSIS = "TREND_ANALYSIS"                # e.g., "How have ticket volumes changed over months?"
    FILTERED_SEARCH = "FILTERED_SEARCH"              # e.g., "List all unresolved critical billing tickets"
    ANOMALY_OR_OUTLIER = "ANOMALY_OR_OUTLIER"        # e.g., "Which tickets took longer than 50 hours to resolve?"


class MetricType(str, Enum):
    """Supported deterministic aggregations."""
    COUNT = "count"
    AVG_RESPONSE_TIME = "avg_response_time"
    AVG_RESOLUTION_TIME = "avg_resolution_time"
    AVG_RATING = "avg_rating"
    RESOLUTION_RATE = "resolution_rate"
    ESCALATION_RATE = "escalation_rate"
    SLA_BREACH_COUNT = "sla_breach_count"
    MIN_RESPONSE_TIME = "min_response_time"
    MAX_RESPONSE_TIME = "max_response_time"
    MIN_RESOLUTION_TIME = "min_resolution_time"
    MAX_RESOLUTION_TIME = "max_resolution_time"


class DimensionType(str, Enum):
    """Supported grouping dimensions."""
    CATEGORY = "category"
    PRIORITY = "priority"
    STATUS = "status"
    AGENT_ID = "agent_id"
    MONTH = "month"
    WEEK = "week"
    DATE = "date"


class FilterOperator(str, Enum):
    """Safe comparison operators."""
    EQ = "eq"          # =
    NEQ = "neq"        # !=
    IN = "in"          # IN (...)
    NOT_IN = "not_in"  # NOT IN (...)
    GT = "gt"          # >
    GTE = "gte"        # >=
    LT = "lt"          # <
    LTE = "lte"        # <=
    LIKE = "like"      # ILIKE / LIKE
    IS_NULL = "is_null"# IS NULL
    NOT_NULL = "not_null" # IS NOT NULL


class FilterCondition(BaseModel):
    """Safe parameterized filter clause."""
    field: str = Field(..., description="Target column name, e.g., category, priority, status, agent_id")
    operator: FilterOperator = Field(FilterOperator.EQ, description="Comparison operator")
    value: Optional[Union[str, int, float, List[Union[str, int, float]]]] = Field(
        None, description="Literal filter value"
    )

    @field_validator("field")
    @classmethod
    def validate_allowed_field(cls, v: str) -> str:
        allowed = {
            "ticket_id", "category", "priority", "status", 
            "agent_id", "response_time_hrs", "resolution_time_hrs", 
            "customer_rating", "created_at", "issue_summary"
        }
        clean = v.strip().lower()
        if clean not in allowed:
            raise ValueError(f"Invalid filter field '{v}'. Allowed fields: {allowed}")
        return clean


class SortOrder(str, Enum):
    ASC = "asc"
    DESC = "desc"


class SortSpec(BaseModel):
    """Sorting specification."""
    field: str = Field(..., description="Column or alias to sort by")
    order: SortOrder = Field(SortOrder.DESC, description="Sorting direction")


class DateRange(BaseModel):
    """Date boundary filters."""
    start_date: Optional[datetime] = None
    end_date: Optional[datetime] = None


class StructuredQuery(BaseModel):
    """
    STRICT structured query schema generated by LLM and validated by backend.
    
    This guarantees:
    1. Zero arbitrary SQL execution.
    2. Strict enum-checked metrics & dimensions.
    3. Parameterized execution in repository layer.
    """
    intent: QueryIntent = Field(QueryIntent.METRIC_AGGREGATION, description="Classified intent")
    metrics: List[MetricType] = Field(
        default_factory=lambda: [MetricType.COUNT],
        description="List of aggregation metrics to calculate"
    )
    group_by: List[DimensionType] = Field(
        default_factory=list,
        description="Grouping dimensions"
    )
    filters: List[FilterCondition] = Field(
        default_factory=list,
        description="Filter predicates"
    )
    date_range: Optional[DateRange] = None
    sort: Optional[SortSpec] = None
    limit: Optional[int] = Field(100, ge=1, le=1000, description="Max rows returned")
    natural_language_question: Optional[str] = Field(None, description="Original user prompt")


class StructuredQueryResult(BaseModel):
    """Output format of deterministic Python query execution."""
    intent: QueryIntent
    query_spec: StructuredQuery
    metrics_summary: Dict[str, Any] = Field(default_factory=dict)
    breakdown_data: List[Dict[str, Any]] = Field(default_factory=list)
    total_records_matched: int = 0
    execution_time_ms: float = 0.0
    explanation: Optional[str] = None
